name: CMake on a single platform

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v4

    # Step 2: Install dependencies
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++

    # Step 3: Configure the project with CMake
    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    # Step 4: Build the project
    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    # Step 5: Run tests
    - name: Test
      working-directory: build
      run: ctest --output-on-failure -C ${{env.BUILD_TYPE}}
